### ISSUE TITLE
ZSQL Connection "Browse" tab fails

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/DocumentTemplate#45]
```
Traceback (most recent call last):
  File "/Users/jens/src/.eggs/waitress-1.2.1-py3.7.egg/waitress/channel.py", line 336, in service
    task.service()
  File "/Users/jens/src/.eggs/waitress-1.2.1-py3.7.egg/waitress/task.py", line 175, in service
    self.execute()
  File "/Users/jens/src/.eggs/waitress-1.2.1-py3.7.egg/waitress/task.py", line 452, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/Users/jens/src/.eggs/Paste-3.0.8-py3.7.egg/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/Users/jens/src/Zope/src/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/Users/jens/src/Zope/src/ZPublisher/WSGIPublisher.py", line 296, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/jens/src/Zope/src/ZPublisher/WSGIPublisher.py", line 230, in publish
    bind=1)
  File "/Users/jens/src/Zope/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/Users/jens/src/Zope/src/ZPublisher/WSGIPublisher.py", line 59, in call_object
    return obj(*args)
  File "/Users/jens/src/Zope/src/App/special_dtml.py", line 101, in __call__
    *(self,) + args[1:], **kw)
  File "/Users/jens/src/DocumentTemplate/src/DocumentTemplate/DT_String.py", line 521, in __call__
    encoding=self.encoding)
  File "/Users/jens/src/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 144, in render_blocks
    render_blocks_(blocks, rendered, md, encoding)
  File "/Users/jens/src/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 245, in render_blocks_
    block = block(md)
  File "/Users/jens/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 116, in render
    return tpRender(v, md, self.section, self.args)
  File "/Users/jens/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 242, in tpRender
    section, md, treeData, level, args, encoding=encoding)
  File "/Users/jens/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 510, in tpRenderTABLE
    colspan, section, md, treeData, level, args)
  File "/Users/jens/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 373, in tpRenderTABLE
    s = encode_str(compress(json.dumps(diff)))  # bytes in ASCII enc.
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

**Comment by dataflake** [comment]
Fixed by a0b06278579320b37095f6d9bc06ef813c83cf2c
